---
- name: Bootstrap script
  hosts: myserver
  become: yes

  tasks:
  - name: Update apt cache
    apt: update_cache=yes
    notify: restart machine
  - name: Upgrade apt packages
    apt: upgrade=yes
    
  handlers:
  - name: restart machine
    shell: reboot now
