---
- name: Bootstrap script
  hosts: myserver
  become: yes

  tasks:
  - name: Update apt cache
    apt: update_cache=yes
  - name: Upgrade apt packages
    apt: upgrade=yes
#    notify:
#    - restart machine

  handlers:
  - name: rebooting machine
    shell: reboot now  
